// Generated by scripts/generate-sdk-types.ts — do not edit by hand.
//
// Source of truth: src/platform/entrypoints/sdk/coreSchemas.ts. To change a type,
// edit the zod schema there and re-run:
//
//   bun run scripts/generate-sdk-types.ts
//
// 125 types are exported from this file.

import type { z } from 'zod/v4'
import type {
  Message as APIAssistantMessage,
  MessageParam,
  RawMessageStreamEvent,
} from '@anthropic-ai/sdk/resources/messages.mjs'
import type { NonNullableUsage } from 'src/platform/entrypoints/sdk/sdkUtilityTypes.js'
import type * as coreSchemas from 'src/platform/entrypoints/sdk/coreSchemas.js'

// ============================================================================
// Usage & Model Types
// ============================================================================

export type ModelUsage = z.infer<
  ReturnType<typeof coreSchemas.ModelUsageSchema>
>

// ============================================================================
// Output Format Types
// ============================================================================

export type OutputFormatType = z.infer<
  ReturnType<typeof coreSchemas.OutputFormatTypeSchema>
>

export type BaseOutputFormat = z.infer<
  ReturnType<typeof coreSchemas.BaseOutputFormatSchema>
>

export type JsonSchemaOutputFormat = z.infer<
  ReturnType<typeof coreSchemas.JsonSchemaOutputFormatSchema>
>

export type OutputFormat = JsonSchemaOutputFormat

// ============================================================================
// Config Types
// ============================================================================

export type ApiKeySource = z.infer<
  ReturnType<typeof coreSchemas.ApiKeySourceSchema>
>

export type ConfigScope = z.infer<
  ReturnType<typeof coreSchemas.ConfigScopeSchema>
>

export type SdkBeta = z.infer<ReturnType<typeof coreSchemas.SdkBetaSchema>>

export type ThinkingAdaptive = z.infer<
  ReturnType<typeof coreSchemas.ThinkingAdaptiveSchema>
>

export type ThinkingEnabled = z.infer<
  ReturnType<typeof coreSchemas.ThinkingEnabledSchema>
>

export type ThinkingDisabled = z.infer<
  ReturnType<typeof coreSchemas.ThinkingDisabledSchema>
>

export type ThinkingConfig = z.infer<
  ReturnType<typeof coreSchemas.ThinkingConfigSchema>
>

// ============================================================================
// MCP Server Config Types (serializable only)
// ============================================================================

export type McpStdioServerConfig = z.infer<
  ReturnType<typeof coreSchemas.McpStdioServerConfigSchema>
>

export type McpSSEServerConfig = z.infer<
  ReturnType<typeof coreSchemas.McpSSEServerConfigSchema>
>

export type McpHttpServerConfig = z.infer<
  ReturnType<typeof coreSchemas.McpHttpServerConfigSchema>
>

export type McpSdkServerConfig = z.infer<
  ReturnType<typeof coreSchemas.McpSdkServerConfigSchema>
>

export type McpServerConfigForProcessTransport = z.infer<
  ReturnType<typeof coreSchemas.McpServerConfigForProcessTransportSchema>
>

export type McpClaudeAIProxyServerConfig = z.infer<
  ReturnType<typeof coreSchemas.McpClaudeAIProxyServerConfigSchema>
>

export type McpServerStatusConfig =
  | McpServerConfigForProcessTransport
  | McpClaudeAIProxyServerConfig

export type McpServerStatus = z.infer<
  ReturnType<typeof coreSchemas.McpServerStatusSchema>
>

export type McpSetServersResult = z.infer<
  ReturnType<typeof coreSchemas.McpSetServersResultSchema>
>

// ============================================================================
// Permission Types
// ============================================================================

export type PermissionUpdateDestination = z.infer<
  ReturnType<typeof coreSchemas.PermissionUpdateDestinationSchema>
>

export type PermissionBehavior = z.infer<
  ReturnType<typeof coreSchemas.PermissionBehaviorSchema>
>

export type PermissionRuleValue = z.infer<
  ReturnType<typeof coreSchemas.PermissionRuleValueSchema>
>

export type PermissionUpdate = z.infer<
  ReturnType<typeof coreSchemas.PermissionUpdateSchema>
>

export type PermissionDecisionClassification = z.infer<
  ReturnType<typeof coreSchemas.PermissionDecisionClassificationSchema>
>

export type PermissionResult = z.infer<
  ReturnType<typeof coreSchemas.PermissionResultSchema>
>

export type PermissionMode = z.infer<
  ReturnType<typeof coreSchemas.PermissionModeSchema>
>

// ============================================================================
// Hook Types
// ============================================================================

export type HookEvent = z.infer<ReturnType<typeof coreSchemas.HookEventSchema>>

export type BaseHookInput = z.infer<
  ReturnType<typeof coreSchemas.BaseHookInputSchema>
>

export type PreToolUseHookInput = z.infer<
  ReturnType<typeof coreSchemas.PreToolUseHookInputSchema>
>

export type PermissionRequestHookInput = z.infer<
  ReturnType<typeof coreSchemas.PermissionRequestHookInputSchema>
>

export type PostToolUseHookInput = z.infer<
  ReturnType<typeof coreSchemas.PostToolUseHookInputSchema>
>

export type PostToolUseFailureHookInput = z.infer<
  ReturnType<typeof coreSchemas.PostToolUseFailureHookInputSchema>
>

export type PermissionDeniedHookInput = z.infer<
  ReturnType<typeof coreSchemas.PermissionDeniedHookInputSchema>
>

export type NotificationHookInput = z.infer<
  ReturnType<typeof coreSchemas.NotificationHookInputSchema>
>

export type UserPromptSubmitHookInput = z.infer<
  ReturnType<typeof coreSchemas.UserPromptSubmitHookInputSchema>
>

export type SessionStartHookInput = z.infer<
  ReturnType<typeof coreSchemas.SessionStartHookInputSchema>
>

export type SetupHookInput = z.infer<
  ReturnType<typeof coreSchemas.SetupHookInputSchema>
>

export type StopHookInput = z.infer<
  ReturnType<typeof coreSchemas.StopHookInputSchema>
>

export type StopFailureHookInput = z.infer<
  ReturnType<typeof coreSchemas.StopFailureHookInputSchema>
>

export type SubagentStartHookInput = z.infer<
  ReturnType<typeof coreSchemas.SubagentStartHookInputSchema>
>

export type SubagentStopHookInput = z.infer<
  ReturnType<typeof coreSchemas.SubagentStopHookInputSchema>
>

export type PreCompactHookInput = z.infer<
  ReturnType<typeof coreSchemas.PreCompactHookInputSchema>
>

export type PostCompactHookInput = z.infer<
  ReturnType<typeof coreSchemas.PostCompactHookInputSchema>
>

export type TeammateIdleHookInput = z.infer<
  ReturnType<typeof coreSchemas.TeammateIdleHookInputSchema>
>

export type TaskCreatedHookInput = z.infer<
  ReturnType<typeof coreSchemas.TaskCreatedHookInputSchema>
>

export type TaskCompletedHookInput = z.infer<
  ReturnType<typeof coreSchemas.TaskCompletedHookInputSchema>
>

export type ElicitationHookInput = z.infer<
  ReturnType<typeof coreSchemas.ElicitationHookInputSchema>
>

export type ElicitationResultHookInput = z.infer<
  ReturnType<typeof coreSchemas.ElicitationResultHookInputSchema>
>

export type ConfigChangeHookInput = z.infer<
  ReturnType<typeof coreSchemas.ConfigChangeHookInputSchema>
>

export type InstructionsLoadedHookInput = z.infer<
  ReturnType<typeof coreSchemas.InstructionsLoadedHookInputSchema>
>

export type WorktreeCreateHookInput = z.infer<
  ReturnType<typeof coreSchemas.WorktreeCreateHookInputSchema>
>

export type WorktreeRemoveHookInput = z.infer<
  ReturnType<typeof coreSchemas.WorktreeRemoveHookInputSchema>
>

export type CwdChangedHookInput = z.infer<
  ReturnType<typeof coreSchemas.CwdChangedHookInputSchema>
>

export type FileChangedHookInput = z.infer<
  ReturnType<typeof coreSchemas.FileChangedHookInputSchema>
>

export type ExitReason = z.infer<
  ReturnType<typeof coreSchemas.ExitReasonSchema>
>

export type SessionEndHookInput = z.infer<
  ReturnType<typeof coreSchemas.SessionEndHookInputSchema>
>

export type HookInput = z.infer<ReturnType<typeof coreSchemas.HookInputSchema>>

export type AsyncHookJSONOutput = z.infer<
  ReturnType<typeof coreSchemas.AsyncHookJSONOutputSchema>
>

export type PreToolUseHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.PreToolUseHookSpecificOutputSchema>
>

export type UserPromptSubmitHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.UserPromptSubmitHookSpecificOutputSchema>
>

export type SessionStartHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.SessionStartHookSpecificOutputSchema>
>

export type SetupHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.SetupHookSpecificOutputSchema>
>

export type SubagentStartHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.SubagentStartHookSpecificOutputSchema>
>

export type PostToolUseHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.PostToolUseHookSpecificOutputSchema>
>

export type PostToolUseFailureHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.PostToolUseFailureHookSpecificOutputSchema>
>

export type PermissionDeniedHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.PermissionDeniedHookSpecificOutputSchema>
>

export type NotificationHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.NotificationHookSpecificOutputSchema>
>

export type PermissionRequestHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.PermissionRequestHookSpecificOutputSchema>
>

export type CwdChangedHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.CwdChangedHookSpecificOutputSchema>
>

export type FileChangedHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.FileChangedHookSpecificOutputSchema>
>

export type SyncHookJSONOutput = z.infer<
  ReturnType<typeof coreSchemas.SyncHookJSONOutputSchema>
>

export type ElicitationHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.ElicitationHookSpecificOutputSchema>
>

export type ElicitationResultHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.ElicitationResultHookSpecificOutputSchema>
>

export type WorktreeCreateHookSpecificOutput = z.infer<
  ReturnType<typeof coreSchemas.WorktreeCreateHookSpecificOutputSchema>
>

export type HookJSONOutput = AsyncHookJSONOutput | SyncHookJSONOutput

export type PromptRequestOption = z.infer<
  ReturnType<typeof coreSchemas.PromptRequestOptionSchema>
>

export type PromptRequest = z.infer<
  ReturnType<typeof coreSchemas.PromptRequestSchema>
>

export type PromptResponse = z.infer<
  ReturnType<typeof coreSchemas.PromptResponseSchema>
>

// ============================================================================
// Skill/Command Types
// ============================================================================

export type SlashCommand = z.infer<
  ReturnType<typeof coreSchemas.SlashCommandSchema>
>

export type AgentInfo = z.infer<ReturnType<typeof coreSchemas.AgentInfoSchema>>

export type ModelInfo = z.infer<ReturnType<typeof coreSchemas.ModelInfoSchema>>

export type AccountInfo = z.infer<
  ReturnType<typeof coreSchemas.AccountInfoSchema>
>

// ============================================================================
// Agent Definition Types
// ============================================================================

export type AgentMcpServerSpec = z.infer<
  ReturnType<typeof coreSchemas.AgentMcpServerSpecSchema>
>

export type AgentDefinition = z.infer<
  ReturnType<typeof coreSchemas.AgentDefinitionSchema>
>

// ============================================================================
// Settings Types
// ============================================================================

export type SettingSource = z.infer<
  ReturnType<typeof coreSchemas.SettingSourceSchema>
>

export type SdkPluginConfig = z.infer<
  ReturnType<typeof coreSchemas.SdkPluginConfigSchema>
>

// ============================================================================
// Rewind Types
// ============================================================================

export type RewindFilesResult = z.infer<
  ReturnType<typeof coreSchemas.RewindFilesResultSchema>
>

// ============================================================================
// External Type Placeholders
// ============================================================================

// ============================================================================
// SDK Message Types
// ============================================================================

export type SDKAssistantMessageError = z.infer<
  ReturnType<typeof coreSchemas.SDKAssistantMessageErrorSchema>
>

export type SDKStatus = z.infer<ReturnType<typeof coreSchemas.SDKStatusSchema>>

export type SDKUserMessage = Omit<
  z.infer<ReturnType<typeof coreSchemas.SDKUserMessageSchema>>,
  'message'
> & {
  message: MessageParam
}

export type SDKUserMessageReplay = Omit<
  z.infer<ReturnType<typeof coreSchemas.SDKUserMessageReplaySchema>>,
  'message'
> & {
  message: MessageParam
}

export type SDKRateLimitInfo = z.infer<
  ReturnType<typeof coreSchemas.SDKRateLimitInfoSchema>
>

export type SDKAssistantMessage = Omit<
  z.infer<ReturnType<typeof coreSchemas.SDKAssistantMessageSchema>>,
  'message'
> & {
  message: APIAssistantMessage
}

export type SDKRateLimitEvent = z.infer<
  ReturnType<typeof coreSchemas.SDKRateLimitEventSchema>
>

export type SDKStreamlinedTextMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKStreamlinedTextMessageSchema>
>

export type SDKStreamlinedToolUseSummaryMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKStreamlinedToolUseSummaryMessageSchema>
>

export type SDKPermissionDenial = z.infer<
  ReturnType<typeof coreSchemas.SDKPermissionDenialSchema>
>

export type SDKResultSuccess = Omit<
  z.infer<ReturnType<typeof coreSchemas.SDKResultSuccessSchema>>,
  'usage'
> & {
  usage: NonNullableUsage
}

export type SDKResultError = Omit<
  z.infer<ReturnType<typeof coreSchemas.SDKResultErrorSchema>>,
  'usage'
> & {
  usage: NonNullableUsage
}

export type SDKResultMessage = SDKResultSuccess | SDKResultError

export type SDKSystemMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKSystemMessageSchema>
>

export type SDKPartialAssistantMessage = Omit<
  z.infer<ReturnType<typeof coreSchemas.SDKPartialAssistantMessageSchema>>,
  'event'
> & {
  event: RawMessageStreamEvent
}

export type SDKCompactBoundaryMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKCompactBoundaryMessageSchema>
>

export type SDKStatusMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKStatusMessageSchema>
>

export type SDKPostTurnSummaryMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKPostTurnSummaryMessageSchema>
>

export type SDKAPIRetryMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKAPIRetryMessageSchema>
>

export type SDKLocalCommandOutputMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKLocalCommandOutputMessageSchema>
>

export type SDKHookStartedMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKHookStartedMessageSchema>
>

export type SDKHookProgressMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKHookProgressMessageSchema>
>

export type SDKHookResponseMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKHookResponseMessageSchema>
>

export type SDKToolProgressMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKToolProgressMessageSchema>
>

export type SDKAuthStatusMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKAuthStatusMessageSchema>
>

export type SDKFilesPersistedEvent = z.infer<
  ReturnType<typeof coreSchemas.SDKFilesPersistedEventSchema>
>

export type SDKTaskNotificationMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKTaskNotificationMessageSchema>
>

export type SDKTaskStartedMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKTaskStartedMessageSchema>
>

export type SDKSessionStateChangedMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKSessionStateChangedMessageSchema>
>

export type SDKTaskProgressMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKTaskProgressMessageSchema>
>

export type SDKToolUseSummaryMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKToolUseSummaryMessageSchema>
>

export type SDKElicitationCompleteMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKElicitationCompleteMessageSchema>
>

/** @internal */
export type SDKPromptSuggestionMessage = z.infer<
  ReturnType<typeof coreSchemas.SDKPromptSuggestionMessageSchema>
>

// ============================================================================
// Session Listing Types
// ============================================================================

export type SDKSessionInfo = z.infer<
  ReturnType<typeof coreSchemas.SDKSessionInfoSchema>
>

export type SDKMessage =
  | SDKAssistantMessage
  | SDKUserMessage
  | SDKUserMessageReplay
  | SDKResultMessage
  | SDKSystemMessage
  | SDKPartialAssistantMessage
  | SDKCompactBoundaryMessage
  | SDKStatusMessage
  | SDKAPIRetryMessage
  | SDKLocalCommandOutputMessage
  | SDKHookStartedMessage
  | SDKHookProgressMessage
  | SDKHookResponseMessage
  | SDKToolProgressMessage
  | SDKAuthStatusMessage
  | SDKTaskNotificationMessage
  | SDKTaskStartedMessage
  | SDKTaskProgressMessage
  | SDKSessionStateChangedMessage
  | SDKFilesPersistedEvent
  | SDKToolUseSummaryMessage
  | SDKRateLimitEvent
  | SDKElicitationCompleteMessage
  | SDKPromptSuggestionMessage

export type FastModeState = z.infer<
  ReturnType<typeof coreSchemas.FastModeStateSchema>
>
