/**
 * Session-wide record of the rate limit that is currently in force, for any
 * provider. The transport publishes it when a 429 stops a turn and clears it
 * on the next successful request; the REPL reads it to render the countdown
 * and to decide when the interrupted work can resume.
 *
 * Mirrors the shape of `claudeAiLimits`'s `currentLimits`/`statusListeners`
 * pair, and keeps React out of the transport path the same way — the hook
 * lives in rateLimitStateHook.ts.
 */

import type { RateLimitInfo } from 'src/providers/rateLimitInfo.js'

export type ProviderRateLimit = RateLimitInfo & {
  /** Display name of the provider that rejected the request. */
  providerLabel: string
  /**
   * The model whose request was rejected. A session runs several — the main
   * loop, the small fast model, subagents — and their limits are independent,
   * so a success on one must not clear a limit recorded for another.
   */
  model: string
  /** When this was observed, epoch ms. */
  observedAtMs: number
}

type Listener = (limit: ProviderRateLimit | null) => void

let currentLimit: ProviderRateLimit | null = null
const listeners = new Set<Listener>()

export function getProviderRateLimit(): ProviderRateLimit | null {
  return currentLimit
}

export function subscribeToProviderRateLimit(listener: Listener): () => void {
  listeners.add(listener)
  return () => {
    listeners.delete(listener)
  }
}

function notify(): void {
  for (const listener of listeners) listener(currentLimit)
}

export function publishProviderRateLimit(limit: ProviderRateLimit): void {
  currentLimit = limit
  notify()
}

/**
 * Drop the record outright. For the resume path, which has just decided to
 * send the request that supersedes it.
 */
export function clearProviderRateLimit(): void {
  if (currentLimit === null) return
  currentLimit = null
  notify()
}

/**
 * Called on every successful request, so a limit that lifts earlier than its
 * reported reset does not leave a stale clock on screen — but only for the
 * model that was limited. A title generated by the small fast model says
 * nothing about the main loop's quota.
 *
 * A no-op when nothing is set, so the hot path costs one null check.
 */
export function clearProviderRateLimitForModel(model: string): void {
  if (currentLimit === null) return
  if (currentLimit.model !== model) return
  currentLimit = null
  notify()
}
