import { resetTurnTokenState } from 'src/platform/bootstrap/state/cost.js'
import {
  getInitialState,
  STATE,
} from 'src/platform/bootstrap/state/store.js'
import type { State } from 'src/platform/bootstrap/state/types.js'

export type {
  AttributedCounter,
  ChannelEntry,
  InvokedSkillInfo,
  SessionCronTask,
  SessionWakeup,
} from 'src/platform/bootstrap/state/types.js'
export {
  notifyRuntimeStateChange,
  onRuntimeStateChange,
} from 'src/platform/bootstrap/state/store.js'
export {
  clearBetaHeaderLatches,
  clearSystemPromptSectionState,
  getAdditionalDirectoriesForClaudeMd,
  getAfkModeHeaderLatched,
  getAllowedChannels,
  getDeferredDeltaLegacySession,
  getFastModeHeaderLatched,
  getHasDevChannels,
  getLargeSystemPromptDetected,
  getLastEmittedDate,
  getPromptId,
  getReplBridgeHandle,
  getSessionEpochMs,
  getSystemPromptSectionCache,
  getThinkingClearLatched,
  isLspDeferLatched,
  isReplBridgeActive,
  latchLspDefer,
  setAdditionalDirectoriesForClaudeMd,
  setAfkModeHeaderLatched,
  setAllowedChannels,
  setDeferredDeltaLegacySession,
  setFastModeHeaderLatched,
  setHasDevChannels,
  setLargeSystemPromptDetected,
  setLastEmittedDate,
  setPromptId,
  setSystemPromptSectionCacheEntry,
  setThinkingClearLatched,
} from 'src/platform/bootstrap/state/latches.js'
export {
  getParentSessionId,
  getSessionId,
  getSessionProjectDir,
  onSessionSwitch,
  regenerateSessionId,
  switchSession,
} from 'src/platform/bootstrap/state/session.js'
export {
  getCwdState,
  getDirectConnectServerUrl,
  getOriginalCwd,
  getProjectRoot,
  setCwdState,
  setDirectConnectServerUrl,
  setOriginalCwd,
  setProjectRoot,
} from 'src/platform/bootstrap/state/cwd.js'
export {
  addToToolDuration,
  addToTotalCostState,
  addToTotalDurationState,
  addToTotalLinesChanged,
  addToTurnClassifierDuration,
  addToTurnHookDuration,
  consumePostCompaction,
  flushInteractionTime,
  getBudgetContinuationCount,
  getCurrentTurnTokenBudget,
  getInitialMainLoopModel,
  getIsScrollDraining,
  getLastApiCompletionTimestamp,
  getLastInteractionTime,
  getLastMainRequestId,
  getMainLoopModelOverride,
  getModelStrings,
  getModelUsage,
  getSdkBetas,
  getStatsStore,
  getTotalAPIDuration,
  getTotalAPIDurationWithoutRetries,
  getTotalCacheCreationInputTokens,
  getTotalCacheReadInputTokens,
  getTotalCostUSD,
  getTotalDuration,
  getTotalInputTokens,
  getTotalLinesAdded,
  getTotalLinesRemoved,
  getTotalOutputTokens,
  getTotalToolDuration,
  getTotalWebSearchRequests,
  getTurnClassifierCount,
  getTurnClassifierDurationMs,
  getTurnHookCount,
  getTurnHookDurationMs,
  getTurnOutputTokens,
  getTurnToolCount,
  getTurnToolDurationMs,
  getUsageForModel,
  hasUnknownModelCost,
  incrementBudgetContinuationCount,
  markPostCompaction,
  markScrollActivity,
  markTurnEnd,
  markTurnStart,
  resetCostState,
  resetModelStringsForTestingOnly,
  resetTotalDurationStateAndCost_FOR_TESTS_ONLY,
  resetTurnClassifierDuration,
  resetTurnHookDuration,
  resetTurnToolDuration,
  setCostStateForRestore,
  setHasUnknownModelCost,
  setInitialMainLoopModel,
  setLastApiCompletionTimestamp,
  setLastMainRequestId,
  setMainLoopModelOverride,
  setModelStrings,
  setSdkBetas,
  setStatsStore,
  snapshotOutputTokensForTurn,
  updateLastInteractionTime,
  waitForScrollIdle,
} from 'src/platform/bootstrap/state/cost.js'
export {
  getActiveTimeCounter,
  getCodeEditToolDecisionCounter,
  getCommitCounter,
  getCostCounter,
  getEventLogger,
  getLocCounter,
  getLoggerProvider,
  getMeter,
  getMeterProvider,
  getPrCounter,
  getSessionCounter,
  getTokenCounter,
  getTracerProvider,
  setEventLogger,
  setLoggerProvider,
  setMeter,
  setMeterProvider,
  setTracerProvider,
} from 'src/platform/bootstrap/state/telemetry.js'
export {
  getAgentColorMap,
  getAllowedSettingSources,
  getApiKeyFromFd,
  getClientType,
  getFlagSettingsInline,
  getFlagSettingsPath,
  getInlinePlugins,
  getIsInteractive,
  getIsNonInteractiveSession,
  getKairosActive,
  getOauthTokenFromFd,
  getQuestionPreviewFormat,
  getScheduledTasksEnabled,
  getSdkAgentProgressSummariesEnabled,
  getSessionBypassPermissionsMode,
  getSessionIngressToken,
  getSessionSource,
  getStrictToolResultPairing,
  getUseCoworkPlugins,
  getUserMsgOptIn,
  preferThirdPartyAuthentication,
  setAllowedSettingSources,
  setApiKeyFromFd,
  setClientType,
  setFlagSettingsInline,
  setFlagSettingsPath,
  setInlinePlugins,
  setIsInteractive,
  setKairosActive,
  setOauthTokenFromFd,
  setQuestionPreviewFormat,
  setScheduledTasksEnabled,
  setSdkAgentProgressSummariesEnabled,
  setSessionBypassPermissionsMode,
  setSessionIngressToken,
  setSessionSource,
  setStrictToolResultPairing,
  setUseCoworkPlugins,
  setUserMsgOptIn,
} from 'src/platform/bootstrap/state/sessionFlags.js'
export {
  addToInMemoryErrorLog,
  clearRegisteredHooks,
  clearRegisteredPluginHooks,
  getCachedClaudeMdContent,
  getInitJsonSchema,
  getLastAPIRequest,
  getLastAPIRequestMessages,
  getLastClassifierRequests,
  getRegisteredHooks,
  registerHookCallbacks,
  resetSdkInitState,
  setCachedClaudeMdContent,
  setInitJsonSchema,
  setLastAPIRequest,
  setLastAPIRequestMessages,
  setLastClassifierRequests,
} from 'src/platform/bootstrap/state/sdkHooks.js'
export {
  addInvokedSkill,
  addSessionCronTask,
  addSlowOperation,
  clearInvokedSkills,
  clearInvokedSkillsForAgent,
  clearPendingSessionWakeup,
  getInvokedSkills,
  getInvokedSkillsForAgent,
  getIsRemoteMode,
  getMainThreadAgentType,
  getPendingSessionWakeup,
  getPlanSlugCache,
  getSessionCreatedTeams,
  getSessionCronTasks,
  getSessionTrustAccepted,
  getSlowOperations,
  getTeleportedSessionInfo,
  handleAutoModeTransition,
  handlePlanModeTransition,
  hasExitedPlanModeInSession,
  isSessionPersistenceDisabled,
  markFirstTeleportMessageLogged,
  needsAutoModeExitAttachment,
  needsPlanModeExitAttachment,
  removeSessionCronTasks,
  setHasExitedPlanMode,
  setIsRemoteMode,
  setMainThreadAgentType,
  setNeedsAutoModeExitAttachment,
  setNeedsPlanModeExitAttachment,
  setPendingSessionWakeup,
  setSessionPersistenceDisabled,
  setSessionTrustAccepted,
  setTeleportedSessionInfo,
} from 'src/platform/bootstrap/state/sessionArtifacts.js'

// Only used in tests
export function resetStateForTests(): void {
  if (process.env.NODE_ENV !== 'test') {
    throw new Error('resetStateForTests can only be called in tests')
  }
  Object.entries(getInitialState()).forEach(([key, value]) => {
    STATE[key as keyof State] = value as never
  })
  resetTurnTokenState()
  // Deliberately NOT sessionSwitched.clear(). Its three subscribers —
  // stableStubState's clipped-id map, loopSentinels' first-fire memory,
  // concurrentSessions' PID file — subscribe at module load and never
  // re-subscribe, so clearing here unsubscribed them for the REST of the
  // process: every later file in the same runner then asserted eviction
  // against a dead signal, and whether it broke depended on whether the
  // module happened to load before this call. registerSession() drops its
  // own previous listener now, which is the leak the clear was really for.
}
