/**
 * Regenerates src/providers/model/reasoningCatalogData.ts from models.dev.
 *
 * models.dev publishes, per (provider, model), a `reasoning_options` array —
 * a discriminated union of `{type:'toggle'}`, `{type:'effort',values:[…]}` and
 * `{type:'budget_tokens',min,max}`. That array is the only machine-readable
 * answer to "which effort levels does THIS model on THIS endpoint accept",
 * and it is per-model precise: `glm-5.3-flash` declares `low|high|max` with no
 * `medium`, matching Z.AI's own docs, while `glm-5`/`glm-5.1` declare nothing.
 *
 * We keep only the `effort` option, and only for the providers Claudin has a
 * preset for — 4.7 MB of catalog becomes ~25 KB of module. The trim itself
 * lives in src/providers/model/reasoningCatalogTrim.ts, shared with the
 * opt-in runtime refresh so both produce the identical shape.
 *
 * models.dev is MIT-licensed (sst/models.dev) and carries no separate data
 * license. Its schema lives in that repo at packages/core/src/schema.ts.
 *
 * Run:  bun run codegen:reasoning-catalog
 *       bun run codegen:reasoning-catalog --from /path/to/api.json
 */
import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

import {
  CATALOG_EFFORT_VALUES,
  trimModelsDevCatalog,
  type CatalogEffortValue,
  type CatalogEndpoint,
} from '../../src/providers/model/reasoningCatalogTrim.js'
import { REPO_ROOT } from '../repoRoot.js'

const SOURCE_URL = 'https://models.dev/api.json'
const OUT = join(REPO_ROOT, 'src/providers/model/reasoningCatalogData.ts')

async function loadCatalog(): Promise<unknown> {
  const fromIndex = process.argv.indexOf('--from')
  if (fromIndex !== -1) {
    const path = process.argv[fromIndex + 1]
    if (!path) throw new Error('--from needs a path')
    return JSON.parse(readFileSync(path, 'utf8'))
  }
  const response = await fetch(SOURCE_URL)
  if (!response.ok) {
    throw new Error(`${SOURCE_URL} answered ${response.status}`)
  }
  return response.json()
}

/** Single-quoted literal, to match the surrounding tree's style. */
function q(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

function emit(
  endpoints: readonly CatalogEndpoint[],
  efforts: Record<string, Record<string, CatalogEffortValue[]>>,
): string {
  const endpointLines = endpoints
    .map(e => {
      const segments = e.segments.map(s => (s === null ? 'null' : q(s))).join(', ')
      return `  { id: ${q(e.id)}, host: ${q(e.host)}, segments: [${segments}] },`
    })
    .join('\n')

  const providerLines = Object.keys(efforts)
    .sort()
    .map(provider => {
      const models = efforts[provider]!
      const modelLines = Object.keys(models)
        .sort()
        .map(model => `    ${q(model)}: [${models[model]!.map(q).join(', ')}],`)
        .join('\n')
      return `  ${q(provider)}: {\n${modelLines}\n  },`
    })
    .join('\n')

  return `// GENERATED by scripts/codegen/reasoning-catalog.ts — do not edit by hand.
// Source: ${SOURCE_URL} (sst/models.dev, MIT). Regenerate with
// \`bun run codegen:reasoning-catalog\`.

import type {
  CatalogEffortValue,
  CatalogEndpoint,
} from 'src/providers/model/reasoningCatalogTrim.js'

export const CATALOG_PROVIDER_ENDPOINTS: readonly CatalogEndpoint[] = [
${endpointLines}
]

/**
 * models.dev provider id → model id → the effort levels that model accepts.
 * A model absent from this table declares no \`effort\` reasoning option.
 */
export const CATALOG_MODEL_EFFORTS: Readonly<
  Record<string, Readonly<Record<string, readonly CatalogEffortValue[]>>>
> = {
${providerLines}
}
`
}

async function main(): Promise<void> {
  const trimmed = trimModelsDevCatalog(await loadCatalog())
  for (const ambiguous of trimmed.ambiguous) {
    console.warn(`  skipped ${ambiguous} — claimed by more than one provider`)
  }

  writeFileSync(OUT, emit(trimmed.endpoints, trimmed.efforts), 'utf8')

  const modelCount = Object.values(trimmed.efforts).reduce(
    (total, models) => total + Object.keys(models).length,
    0,
  )
  console.log(
    `reasoning catalog: ${Object.keys(trimmed.efforts).length} providers, ` +
      `${modelCount} models, ${trimmed.endpoints.length} endpoints, ` +
      `${CATALOG_EFFORT_VALUES.length} known levels → ${OUT}`,
  )
}

await main()
